# Change these first
owner: CleverPet # Your GitHub organization or username, where this repository lives
repo: fluentpet_uptime # The name of this repository

sites:
  - name: FluentPet Store
    url: $UPTIME_FP_STORE_URL
  - name: FluentPet Support
    url: $UPTIME_FP_SUPPORT_URL
  - name: FluentPet API
    url: $UPTIME_FP_API_URL
    expectedStatusCodes:
      - 404
      - 200
      - 201

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fluent.pet
  publish: true
  name: ""
  logoUrl: https://cdn.shopify.com/s/files/1/0397/2903/7469/files/FluentPet-Wordmark-2022_600x.png
  navbar:
    - title: Status
      href: /
    - title: Store
      href: $UPTIME_FP_STORE_URL

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
